# aerospace.toml
# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    # ---- App Launchers (Omarchy style) ----

    # ---- Window management ----
    alt-q         = "close --quit-if-last-window"
    alt-w         = "close"                                     # Close window

    # Focus movement (wrap-around like i3)
    alt-left      = "focus --boundaries-action wrap-around-the-workspace left"
    alt-down      = "focus --boundaries-action wrap-around-the-workspace down"
    alt-up        = "focus --boundaries-action wrap-around-the-workspace up"
    alt-right     = "focus --boundaries-action wrap-around-the-workspace right"

    alt-shift-left  = "move left"
    alt-shift-down  = "move down"
    alt-shift-up    = "move up"
    alt-shift-right = "move right"

    # Fullscreen (moved off alt-f to avoid Finder conflict)
    alt-f11       = "fullscreen"

    # Layouts
    alt-s         = "layout v_accordion"
    alt-h         = "layout h_accordion"
    alt-shift-space = "layout floating tiling"

    # Workspaces (Omarchy style)
    alt-1         = "workspace 1"
    alt-2         = "workspace 2"
    alt-3         = "workspace 3"
    alt-4         = "workspace 4"
    alt-5         = "workspace 5"
    alt-6         = "workspace 6"

    alt-shift-1   = "move-node-to-workspace 1"
    alt-shift-2   = "move-node-to-workspace 2"
    alt-shift-3   = "move-node-to-workspace 3"
    alt-shift-4   = "move-node-to-workspace 4"
    alt-shift-5   = "move-node-to-workspace 5"
    alt-shift-6   = "move-node-to-workspace 6"

    # Config reload
    alt-shift-c   = "reload-config"

    # Resize mode
    alt-r         = "mode resize"

    # ---- Screenshot / Capture (Omarchy style, macOS native) ----
    # macOS doesn’t have Print key, so use alt+shift+3/4/5 maybe?

    alt-shift-r   = "exec-and-forget screencapture -v ~/Pictures/record.mov"       # record region
    alt-shift-m   = "exec-and-forget screencapture ~/Pictures/record.mov"          # record monitor

    alt-shift-p   = "exec-and-forget osascript -e 'choose color'"                  # color picker

[mode.resize.binding]
    h = "resize width -50"
    j = "resize height +50"
    k = "resize height -50"
    l = "resize width +50"
    enter = "mode main"
    esc = "mode main"